 ```kroki-plantuml
@startuml
title warmouse container light domain diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(Client, "Пользователь умного дома", "Клиент установивший себе приложение умного дома и покупающий подключаемые умные устройства")

Container_Boundary(TemperatureControlSystem, "Система управления температурой") {
    Container(MobileApp, "Мобильное приложение", "Kotlin, Swift", "Мобильное приложение")
    Container(Server, "Бэкенд система управления отоплением развернутая на сервере", "Go", "Серверная часть")
    Container(Sys_Client, "Устройства пользователя", "Embeded", "Клиентская часть")
    Container(Database, "База данных с данными об устройствах и пользователе и их состояниях", "PostgreSQL", "Шардированная БД по признаку управления светом")
}

Rel(Client, MobileApp, "Смотрит актуальную информацию о температуре в помещении")
Rel(Client, MobileApp, "Переключает с помещение а помещение")
Rel(Client, MobileApp, "Включает/Выключает свет в конкретном помещении")
Rel(MobileApp, Server, "Получает актуальное состояние датчиков света для конкретного пользователя")
Rel(MobileApp, Server, "Выполняет воздействие на конкретный датчик конкретного пользователя")
Rel(Server, Database, "Получает данные о датчиках света по конкретному пользователю")
Rel(Server, Sys_Client, "Отправляет запрос воздействие")
Rel(Sys_Client, Server, "Отправляет вебхук о состоянии датчиков")
@enduml
``` 